spring:
  datasource:
    url: jdbc:mysql://localhost:3306/npp?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rest:
    template:
      connect-timeout: 10000  # 10초
      read-timeout: 30000     # 30초
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.nopair: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

gemini:
  api-key: "AIzaSyCt7NJZegCLTrJHFPcEe8qOUXqXdvp83b4"
  api-url: "https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash"
  max-tokens: 1000

github:
  api-token: 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
#  webhook-secret:
  api-url: "https://api.github.com"