spring:
  datasource:
    url: jdbc:mysql://localhost:3306/npp?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rest:
    template:
      connect-timeout: 10000  # 10초
      read-timeout: 30000     # 30초
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.nopairprgm: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

gemini:
  api-key: "AIzaSyCt7NJZegCLTrJHFPcEe8qOUXqXdvp83b4"
  api-url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
  max-tokens: 1000

github:
  api-token: "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"
#  webhook-secret:
  api-url: "https://api.github.com"