package com.blog.nopairprgm.application.service;

import com.blog.nopairprgm.domain.model.CodeReview;
import com.blog.nopairprgm.domain.model.ReviewComment;
import com.blog.nopairprgm.domain.repository.ReviewCommentRepository;
import com.blog.nopairprgm.infrastructure.github.GitHubClient;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class ReviewCommentService {
    private final ReviewCommentRepository reviewCommentRepository;
    private final GitHubClient githubClient;

    @Transactional
    public void createComment(
            CodeReview review,
            String path,
            Integer position,
            String content,
            String commitId
    ) {
        ReviewComment comment = ReviewComment.create(
                review,
                path,
                position,
                content,
                commitId
        );
        reviewCommentRepository.save(comment);
    }

    @Transactional
    public void publishPendingComments() {
        reviewCommentRepository.findByPublishedFalse()
                .forEach(this::publishComment);
    }

    private void publishComment(ReviewComment comment) {
        CodeReview review = comment.getCodeReview();
        String repository = review.getPullRequest().getRepositoryName();
        Long prNumber = review.getPullRequest().getGithubPrId();

        githubClient.createReviewComment(
                repository,
                prNumber,
                comment.getCommitId(),
                comment.getPath(),
                comment.getPosition(),
                formatComment(comment.getContent())
        );

        comment.markAsPublished();
        reviewCommentRepository.save(comment);
    }

    private String formatComment(String content) {
        return """
                ### AI Code Review Comment
                
                %s
                
                ---
                *Generated by No-Pair-Prgm AI Assistant*
                """.formatted(content);
    }
}
